apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: skyn-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: skyn-server
    spec:
      containers:
        - name: skyn-container
          image: weidinger/dobert_skyn:latest
          ports:
            - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: skyn-service
  name: skyn-service
spec:
  ports:
    - port: 9501
      targetPort: 8501
  selector:
    app: skyn-server
  type: LoadBalancer